
local c=require(game:GetService("ReplicatedStorage"):WaitForChild("modules"))local d=c.load("mapping")
return
{id=21,QUEST_VERSION=1,questLineName="Love Sick",questLineImage="",questLineDescription="Gnomeo is tired of Gnometta and Gnoma constantly bothering him.",requireQuests={},repeatableData={value=false},requireClass=
nil,objectives={{requireLevel=34,giverNpcName="Gnomeo",handerNpcName="witch",objectiveName="Love Sick",completedText="Find the witch in Enchanted Forest.",completedNotes="There's a \"funny lady\" somewhere in Enchanted Forest who can help with Gnomeo's problem.",handingNotes="I should talk to the witch.",level=15,expMulti=.1,goldMulti=0,rewards={},hideAlert=true,steps={{triggerType="found-witch",requirement={amount=1},hideAlert=true,hideNote=true}}},{requireLevel=15,giverNpcName="witch",handerNpcName="witch",objectiveName="Love Sick",completedText="Return to witch.",completedNotes="Now that I have all the ingredients, I should return to the witch.",handingNotes="Now I need to get the potion from the witch.",level=16,expMulti=2,goldMulti=0,rewards={},steps={{triggerType="item-collected",requirement={id=30,amount=1},accompanyingNote="Catch of the sea"}}},{requireLevel=1,giverNpcName="witch",handerNpcName="Gnomeo",objectiveName="Love Sick",completedText="Find the witch in Enchanted Forest.",completedNotes="It's time for me to deliver the potion to Gnomeo.",handingNotes="Quest completed!",level=16,expMulti=0,goldMulti=2.5,rewards={},hideAlert=true,steps={{triggerType="item-collected",requirement={id=189,amount=1,hideNote=true,hideAlert=true}}},localOnFinish=function(_a)
spawn(function()
if
workspace:FindFirstChild("Gnomeo")then
workspace:FindFirstChild("Gnomeo").greeting:Destroy()
for ba,ca in
pairs(workspace:FindFirstChild("Gnomeo").pot:GetChildren())do if ca:isA("MeshPart")then ca.Transparency=0 end end
game.CollectionService:RemoveTag(workspace:FindFirstChild("Gnomeo").UpperTorso,"interact")
local aa=workspace:FindFirstChild("Gnomeo").AnimationController:LoadAnimation(workspace:FindFirstChild("Gnomeo").drink)wait(2)aa:Play()wait(1)
workspace:FindFirstChild("Gnomeo").pot.drank.Transparency=1;wait(4)
_a.network:fire("{5F65C927-3FC6-4F76-B110-3EBEA8BFA675}","Gnomeo","ooooo... i dont feel so good")wait(4)end end)end}},dialogueData={responseButtonColor=Color3.fromRGB(255,207,66),dialogue_unassigned_1={{text="heya buddy, i have a problem... gnometta and gnoma wont stop bothering me. i like them and all, but they are really annoying. can you make it so they wont bother me anymore?"}},dialogue_active_1={{text="should not display"}},dialogue_objectiveDone_1={{text="Ahhhhh... a wee gnome with a problem at home..."}},dialogue_unassigned_2={{text="Ack ack ack! A potion of solitary is what I forsee, a mixture of oddity lacking homonegy. If ingredients from Vesteria are what you bring, a potion of Anti-Love you shall receive."}},dialogue_active_2={{text="Returned to me has thee, but lacking ingredients I see."}},dialogue_objectiveDone_2={{text="Fulfilled has been the list, and to work I will be quick..."}},dialogue_unassigned_3={{text="A potion that riddens devotion is what I give. Farewell, may Gnomeo's troubles be hidden in a jiff."}},dialogue_active_3={{text="should not show"}},dialogue_objectiveDone_3={{text="you have a potion that will make gnometta and gnomera stop bothering me? great! give it to me, please!"}},options={{response_unassigned_accept_1="Ok",response_unassigned_decline_1="No",dialogue_unassigned_accept_1={{text="yay! maybe you can try asking that funny lady in the woods to help. thanks buddy!"}},dialogue_unassigned_decline_1={{text="golly gee."}},response_unassigned_accept_2="Makes sense",response_unassigned_decline_2="What?",dialogue_unassigned_accept_2={{text="In your notes you may check for what I need. Complete the deed and from long ago the problem of Gnomeo will be."}},dialogue_unassigned_decline_2={{text="Chicken butt."}},response_unassigned_accept_3="I'll bring it to him",response_unassigned_decline_3="Maybe later",dialogue_unassigned_accept_3={{text="Farewell- Gnomeo will be free, I gaurantee."}},dialogue_unassigned_decline_3={{text="Unwise, your answer you should revise."}}}}}}