
local _a=require(game:GetService("ReplicatedStorage"):WaitForChild("modules"))local aa=_a.load("mapping")local ba=_a.load("network")
local ca=_a.load("utilities")
return
{id=7,QUEST_VERSION=2,questLineName="Rubee Problem",questLineImage="",questLineDescription="Scout Foxtrot reports that the Rubees on the mainland of Scallop Shores are laying new hives. He and the Hunter Scouts need my help.",requireQuests={},repeatableData={value=false,timeInterval=0},requireClass=
nil,objectives={{requireLevel=12,giverNpcName="Scout Foxtrot",handerNpcName="Lieutenant Venessa",objectiveName="Rubee Problem",completedText="Go to the hunter outpost.",completedNotes="I need to bring the Rubee Eye to the Hunter outpost at the end of the mainland jungle path.",handingNotes="Lieutenant Venessa has a task for me.",level=13,expMulti=0.5,goldMulti=0,rewards={},steps={{triggerType="item-collected",requirement={id=95,amount=1}}}},{requireLevel=12,giverNpcName="Lieutenant Venessa",handerNpcName="Lieutenant Venessa",objectiveName="Rubee Problem Part 2",completedText="Return to Lieutenant Venessa.",completedNotes="Now that I have the dynamite, I need to bring it to Lieutenant Venessa",handingNotes="Lieutenant Venessa has my final task.",level=13,expMulti=0.3,goldMulti=0,rewards={},steps={{triggerType="collect-dynamite",requirement={amount=1},overridingNote="Find the dynamite in Scallop Shores"}}},{requireLevel=12,giverNpcName="Lieutenant Venessa",handerNpcName="Lieutenant Venessa",objectiveName="Rubee Problem Part 3",completedText="Return to Lieutenant Venessa.",completedNotes="I have placed the Dynamite charges. Now I should return to Lieutenant Venessa.",handingNotes="Quest completed!",level=14,expMulti=1.65,goldMulti=1,rewards={{id=45,stacks=3},{id=61,stacks=1}},steps={{triggerType="set-rubee-dynamite",requirement={amount=3},accompanyingNote="Dynamite placed"}},serverOnFinish=function(da)
ba:fireAllClients("doRubeeExplosion",da)local _b={}_b.damage=9999999;_b.sourcePlayerId=da.userId
_b.damageTime=os.time()wait(6)local ab=workspace:WaitForChild("explosion1")
local bb=ca.getEntities("monster")local cb={}
for _d,ad in pairs(bb)do if ad.entityId.Value=="Rubee"then
if
(ad.Position-ab.PrimaryPart.Position).magnitude<=80 then table.insert(cb,ad)end end end
spawn(function()wait(.5)for _d,ad in pairs(cb)do
ba:invoke("{031BE66E-62B6-4583-B409-DCB61C0DA077}",da,ad,_b)end end)wait(9)local db=workspace:WaitForChild("explosion2")
local _c=ca.getEntities("monster")local ac={}
for _d,ad in pairs(_c)do if ad.entityId.Value=="Rubee"then
if
(ad.Position-db.PrimaryPart.Position).magnitude<=80 then table.insert(ac,ad)end end end
spawn(function()wait(.5)for _d,ad in pairs(ac)do
ba:invoke("{031BE66E-62B6-4583-B409-DCB61C0DA077}",da,ad,_b)end end)wait(9)local bc=workspace:WaitForChild("explosion3")
local cc=ca.getEntities("monster")local dc={}
for _d,ad in pairs(cc)do if ad.entityId.Value=="Rubee"then
if
(ad.Position-bc.PrimaryPart.Position).magnitude<=80 then table.insert(dc,ad)end end end
spawn(function()wait(.5)for _d,ad in pairs(dc)do
ba:invoke("{031BE66E-62B6-4583-B409-DCB61C0DA077}",da,ad,_b)end end)end}},dialogueData={responseButtonColor=Color3.fromRGB(255,207,66),dialogue_unassigned_1={{text="Roger, Foxtrot reports that the Rubees are laying new hives on the mainland. The hunter outpost must be informed. They'll only trust you if you bring them a"},{text="Rubee Eye.",font=Enum.Font.SourceSansBold},{text="Get moving cadet, over."}},dialogue_active_1={{text="I have no business with you."},{text="(Gather a Rubee Eye)",font=Enum.Font.SourceSansBold}},dialogue_objectiveDone_1={{text="So you say Foxtrot has intel the Rubees are laying new hives? Well, we can't have that..."}},dialogue_unassigned_2={{text="We cannot let the Rubees grow in numbers and launch an attack on the city. When new hives form, protocol is to blow them to smithereens! We, however, are out of explosives. You'll have to find some for us! There's got to be some lying around here in Scallop Shores."}},dialogue_active_2={{text="Have you found the dynamite yet? There's got to be some in Scallop Shores."}},dialogue_objectiveDone_2={{text="Excellent! Now I need you to do one last thing..."}},dialogue_unassigned_3={{text="Admirable work so far, soldier! But our task is not completed. As our most competent recruit, I'll need you to plant the explosives at the three marked charge locations near the hives. Then it's... boom boom for the Rubees."}},dialogue_active_3={{text="Go set up the explosives at the three charge locations. They are marked near the hives."}},dialogue_objectiveDone_3={{text="The explosives are ready? Perfect! BYE BYE BEES!"}},options={{response_unassigned_accept_1="Roger that!",response_unassigned_decline_1="I'm allergic to bees",dialogue_unassigned_accept_1={{text="Copy. Foxtrot appreciates you, over."}},dialogue_unassigned_decline_1={{text="Copy. This is no time for allergies, over."}},response_unassigned_accept_2="M'am yes m'am!",response_unassigned_decline_2="Why don't you do it?",dialogue_unassigned_accept_2={{text="Good soldier!"}},dialogue_unassigned_decline_2={{text="I must stay and defend the outpost! If I'm not here, the Rubees will surely sneak into the city."}},response_unassigned_accept_3="Boom boom bees",response_unassigned_decline_3="Nah, I'm tired",dialogue_unassigned_accept_3={{text="Let's finish this."}},dialogue_unassigned_decline_3={{text="... I thought you were better than that."}}}}}}